repos:
  # Task 1: Format code với black
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Phiên bản của black
    hooks:
      - id: black
        args: [--line-length=88]  # Độ dài dòng tối đa (theo chuẩn PEP 8)

  # Task 1: Check syntax với flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0  # Phiên bản của flake8
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]  # Cấu hình flake8

  # Task 2: Check cú pháp commit message
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check commit message syntax
        entry: /usr/bin/bash scripts/check_commit_message.sh
        language: script
        stages: [commit-msg]
