stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - data/raw/yoochoose-clicks.dat
      - data/test/yoochoose-test.dat
      - scripts/preprocess.py
    outs:
      - data/processed/item_encoder.pkl
      - data/processed/clicks_train.parquet
      - data/processed/clicks_test.parquet
      - data/processed/train_sessions.pkl
      - data/processed/test_sessions.pkl
  train:
    cmd: python scripts/train.py
    deps:
      - data/processed/train_sessions.pkl
      - data/processed/test_sessions.pkl
      - scripts/train.py
    outs:
      - models/model.pth
    metrics:
      - metrics/metrics.json:
          cache: false
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - models/model.pth
      - data/processed/test_sessions.pkl
      - scripts/evaluate.py
    metrics:
      - metrics/eval_metrics.json:
          cache: false
